  merge-branch: 
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@master
    - name: Merge
      uses: devmasx/merge-branch@v1.1.0
      with:
        label_name: 'merged in master'
        target_branch: 'master'
      env:
        GITHUB_TOKEN: ${{secrets.ACTIONS_TOKEN}}