name: WeatherAppCI
#too
on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    # test
      
    steps:
      
    - uses: actions/checkout@v2
      
        
    - name : update cocoapods
      run : sudo gem update cocoapods --pre
    
    - name : update pods file
      run : pod update

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app

    - name: Build and test
      run: xcodebuild clean test -workspace WeatherApp.xcworkspace -scheme "WeatherApp" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11"

    - name: The job has failed
      if: ${{ failure() }}
      run: echo "fail"

    - name: The job has succeeded
      if: ${{ success() }}
      run: |
          git remote update
          git branch
          git checkout master
          git merge develop --allow-unrelated-histories -s yours
          





