name: WeatherAppCI
#too
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    # test
      
    steps:
      
    - uses: actions/checkout@v2
      
        
    - name : update cocoapods
      run : sudo gem update cocoapods --pre
    
    - name : update pods file
      run : pod update

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app

    - name: Build and test
      run: xcodebuild clean test -workspace WeatherApp.xcworkspace -scheme "WeatherApp" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11"

    - name: The job has failed
      if: ${{ failure() }}
      run: echo "Failed test"

    - name: The job has succeeded
      if: ${{ success() }}
    - uses: actions/checkout@master
    - name: Merge by labeled
      uses: devmasx/merge-branch@v1.1.0
      with:
        label_name: 'merged in develop'
        target_branch: 'master'
      env:
        GITHUB_TOKEN: ${{secrets.ACTIONS_TOKEN}}


    