name: WeatherAppCI
#too
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    # test
      
    steps:
      
    - uses: actions/checkout@v2
      
        
    - name : update cocoapods
      run : sudo gem update cocoapods --pre
    
    - name : update pods file
      run : pod update

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app

    - name: Build and test
      run: xcodebuild clean build test -workspace WeatherApp.xcworkspace -scheme "WeatherApp" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11"

    - name: The job has failed
    run: echo "${{ failure() }}"
    