name: Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
#      - name: Archiving project
#        env:
#          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
#        run: ./.github/scripts/archive_app.sh
#      - name: Exporting .ipa
##        run: ./.github/scripts/export_ipa.sh
#        run : xcodebuild -exportArchive -archivePath $PWD/build/WeatherApp.xcarchive -exportOptionsPlist WeatherApp/exportOptions.plist -exportPath $PWD/build
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Build archive
        run: |
         xcodebuild -sdk iphoneos -projec tWeatherApp/WeatherApp.xcworkspace \
          -configuration Release -scheme "WeatherApp" \
          -derivedDataPath DerivedData \
          -archivePath DerivedData/Archive/WeatherApp.xcarchive
      - name: Export Archive
        run: |
         xcodebuild -exportArchive \
          -archivePath DerivedData/Archive/WeatherApp.xcarchive \
          -exportOptionsPlist WeatherApp/exportOptions.plist \
          -exportPath DerivedData/WeatherApp.ipa
#      - name: Publishing app
#        if: success()
#        env:
#          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
#          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
#        run: ./.github/scripts/publish_testflight.sh
